package com.example.lab.mybatis.dao;

import com.example.lab.mybatis.model.Fridge;
import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface FridgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FRIDGE
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FRIDGE
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int insert(Fridge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FRIDGE
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    Fridge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FRIDGE
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    List<Fridge> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FRIDGE
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int updateByPrimaryKey(Fridge record);
}