package com.example.lab.mybatis.dao;

import com.example.lab.mybatis.model.Fridgeproduct;
import java.util.List;

import org.mybatis.cdi.Mapper;

@Mapper
public interface FridgeproductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FRIDGEPRODUCT
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FRIDGEPRODUCT
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int insert(Fridgeproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FRIDGEPRODUCT
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    Fridgeproduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FRIDGEPRODUCT
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    List<Fridgeproduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FRIDGEPRODUCT
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int updateByPrimaryKey(Fridgeproduct record);
}