package com.example.lab.mybatis.dao;

import com.example.lab.mybatis.model.Manufacturer;
import java.util.List;

import org.mybatis.cdi.Mapper;

@Mapper
public interface ManufacturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int insert(Manufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    Manufacturer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    List<Manufacturer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int updateByPrimaryKey(Manufacturer record);
}