package com.example.lab.mybatis.dao;

import com.example.lab.mybatis.model.ProducttypeProduct;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ProducttypeProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCTTYPE_PRODUCT
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int deleteByPrimaryKey(@Param("productId") Integer productId, @Param("producttypeId") Integer producttypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCTTYPE_PRODUCT
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int insert(ProducttypeProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCTTYPE_PRODUCT
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    List<ProducttypeProduct> selectAll();
}