package com.example.lab.mybatis.dao;

import com.example.lab.mybatis.model.Producttype;
import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ProducttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCTTYPE
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCTTYPE
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int insert(Producttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCTTYPE
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    Producttype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCTTYPE
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    List<Producttype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCTTYPE
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    int updateByPrimaryKey(Producttype record);
}