package com.example.lab.mybatis.model;

import com.example.lab.mybatis.model.Product;
import lombok.Getter;
import lombok.Setter;

public class Fridgeproduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FRIDGEPRODUCT.ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FRIDGEPRODUCT.QUANTITY
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FRIDGEPRODUCT.FRIDGE_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private Integer fridgeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FRIDGEPRODUCT.PRODUCT_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FRIDGEPRODUCT.ID
     *
     * @return the value of PUBLIC.FRIDGEPRODUCT.ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FRIDGEPRODUCT.ID
     *
     * @param id the value for PUBLIC.FRIDGEPRODUCT.ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FRIDGEPRODUCT.QUANTITY
     *
     * @return the value of PUBLIC.FRIDGEPRODUCT.QUANTITY
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FRIDGEPRODUCT.QUANTITY
     *
     * @param quantity the value for PUBLIC.FRIDGEPRODUCT.QUANTITY
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FRIDGEPRODUCT.FRIDGE_ID
     *
     * @return the value of PUBLIC.FRIDGEPRODUCT.FRIDGE_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public Integer getFridgeId() {
        return fridgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FRIDGEPRODUCT.FRIDGE_ID
     *
     * @param fridgeId the value for PUBLIC.FRIDGEPRODUCT.FRIDGE_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setFridgeId(Integer fridgeId) {
        this.fridgeId = fridgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FRIDGEPRODUCT.PRODUCT_ID
     *
     * @return the value of PUBLIC.FRIDGEPRODUCT.PRODUCT_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FRIDGEPRODUCT.PRODUCT_ID
     *
     * @param productId the value for PUBLIC.FRIDGEPRODUCT.PRODUCT_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    @Getter @Setter
    public Product product;
}