package com.example.lab.mybatis.model;

import com.example.lab.mybatis.model.Fridgeproduct;
import com.example.lab.mybatis.model.Manufacturer;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import java.util.Set;

public class Fridge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FRIDGE.ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FRIDGE.NAME
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FRIDGE.MANUFACTURER_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private Integer manufacturerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FRIDGE.ID
     *
     * @return the value of PUBLIC.FRIDGE.ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FRIDGE.ID
     *
     * @param id the value for PUBLIC.FRIDGE.ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FRIDGE.NAME
     *
     * @return the value of PUBLIC.FRIDGE.NAME
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FRIDGE.NAME
     *
     * @param name the value for PUBLIC.FRIDGE.NAME
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FRIDGE.MANUFACTURER_ID
     *
     * @return the value of PUBLIC.FRIDGE.MANUFACTURER_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public Integer getManufacturerId() {
        return manufacturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FRIDGE.MANUFACTURER_ID
     *
     * @param manufacturerId the value for PUBLIC.FRIDGE.MANUFACTURER_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setManufacturerId(Integer manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    @Getter @Setter
    public Set<Fridgeproduct> fridgeProducts;

    @Getter @Setter
    private Manufacturer manufacturer;
}