package com.example.lab.mybatis.model;

public class Producttype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCTTYPE.ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCTTYPE.DESCRIPTION
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCTTYPE.NAME
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCTTYPE.ID
     *
     * @return the value of PUBLIC.PRODUCTTYPE.ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCTTYPE.ID
     *
     * @param id the value for PUBLIC.PRODUCTTYPE.ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCTTYPE.DESCRIPTION
     *
     * @return the value of PUBLIC.PRODUCTTYPE.DESCRIPTION
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCTTYPE.DESCRIPTION
     *
     * @param description the value for PUBLIC.PRODUCTTYPE.DESCRIPTION
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCTTYPE.NAME
     *
     * @return the value of PUBLIC.PRODUCTTYPE.NAME
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCTTYPE.NAME
     *
     * @param name the value for PUBLIC.PRODUCTTYPE.NAME
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setName(String name) {
        this.name = name;
    }
}