package com.example.lab.mybatis.model;

public class ProducttypeProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCTTYPE_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCTTYPE_PRODUCT.PRODUCTTYPE_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    private Integer producttypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCTTYPE_PRODUCT.PRODUCT_ID
     *
     * @return the value of PUBLIC.PRODUCTTYPE_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCTTYPE_PRODUCT.PRODUCT_ID
     *
     * @param productId the value for PUBLIC.PRODUCTTYPE_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCTTYPE_PRODUCT.PRODUCTTYPE_ID
     *
     * @return the value of PUBLIC.PRODUCTTYPE_PRODUCT.PRODUCTTYPE_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public Integer getProducttypeId() {
        return producttypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCTTYPE_PRODUCT.PRODUCTTYPE_ID
     *
     * @param producttypeId the value for PUBLIC.PRODUCTTYPE_PRODUCT.PRODUCTTYPE_ID
     *
     * @mbg.generated Sun Mar 23 20:44:10 EET 2025
     */
    public void setProducttypeId(Integer producttypeId) {
        this.producttypeId = producttypeId;
    }
}